[package]
name = "rust_kvs_log"
version = "0.1.0"
edition = "2021"

[dependencies]
assert_cmd = "0.11.0"
clap = { version = "4.5.39", features = ["derive"] }
predicates = "1.0.0"
tempfile = "3.0.7"
walkdir = "2.2.7"

[lib]
test = false
doctest = false
