[package]
name = "rust_kvs_server"
version = "0.1.0"
edition = "2024"

[dependencies]
assert_cmd = "2.0.17"
clap = { version = "4.5.49", features = ["derive"] }
tempfile = "3.23.0"
walkdir = "2.2.7"
log = "0.4.28"
simple_logger = "5.0.0"

[lib]
test = false
doctest = false
