[package]
name = "rust_kvs_server"
version = "0.1.0"
edition = "2024"

[dependencies]
assert_cmd = "0.11.0"
clap = { version = "4.5.39", features = ["derive"] }
predicates = "1.0.0"
tempfile = "3.0.7"
walkdir = "2.2.7"
log = "0.4.27"
simple_logger = "5.0.0"

[lib]
test = false
doctest = false
